# Generated by Django 4.0.3 on 2022-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenimiento', '0003_alter_cargo_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.IntegerField(null=True),
        ),
    ]
